import { NextRequest, NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'

interface RouteParams {
  params: Promise<{ id: string }>
}

export async function GET(_request: NextRequest, { params }: RouteParams) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Verify ownership via user-scoped client (respects RLS)
  const { data: note, error: noteError } = await supabase
    .from('notes')
    .select('id, user_id')
    .eq('id', id)
    .single()

  if (noteError || !note) {
    return NextResponse.json({ error: 'Note not found' }, { status: 404 })
  }

  if (note.user_id !== user.id) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const serviceClient = await createServiceClient()

  const { data: collaborators, error } = await serviceClient
    .from('collaborators')
    .select('*, user_profiles(display_name)')
    .eq('note_id', id)
    .order('created_at', { ascending: true })

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  const result = (collaborators ?? []).map((collab) => {
    const { user_profiles, ...rest } = collab as typeof collab & { user_profiles: { display_name: string | null } | null }
    return {
      ...rest,
      display_name: user_profiles?.display_name ?? null,
    }
  })

  return NextResponse.json({ collaborators: result })
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const body = await request.json()
  const { email, permission } = body

  // Validate email format
  if (!email || typeof email !== 'string') {
    return NextResponse.json({ error: 'Email is required' }, { status: 400 })
  }
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailRegex.test(email)) {
    return NextResponse.json({ error: 'Invalid email format' }, { status: 400 })
  }

  // Validate permission
  if (!permission || !['edit', 'view'].includes(permission)) {
    return NextResponse.json({ error: 'Permission must be edit or view' }, { status: 400 })
  }

  // Verify ownership via user-scoped client
  const { data: note, error: noteError } = await supabase
    .from('notes')
    .select('id, user_id')
    .eq('id', id)
    .single()

  if (noteError || !note) {
    return NextResponse.json({ error: 'Note not found' }, { status: 404 })
  }

  if (note.user_id !== user.id) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  // Check if inviting yourself
  if (user.email && user.email.toLowerCase() === email.toLowerCase()) {
    return NextResponse.json({ error: 'Cannot invite yourself' }, { status: 400 })
  }

  const serviceClient = await createServiceClient()

  // Check if already a collaborator
  const { data: existing } = await serviceClient
    .from('collaborators')
    .select('id')
    .eq('note_id', id)
    .ilike('invited_email', email)
    .single()

  if (existing) {
    return NextResponse.json({ error: 'This email is already a collaborator' }, { status: 409 })
  }

  // Insert collaborator (invite_token auto-generated by DB default)
  const { data: inserted, error: insertError } = await serviceClient
    .from('collaborators')
    .insert({
      note_id: id,
      invited_email: email,
      permission,
      user_id: null,
      accepted_at: null,
    })
    .select()
    .single()

  if (insertError || !inserted) {
    return NextResponse.json({ error: insertError?.message ?? 'Insert failed' }, { status: 500 })
  }

  const token = inserted.invite_token
  const appUrl =
    process.env.NEXT_PUBLIC_APP_URL ??
    request.headers.get('origin') ??
    `https://${request.headers.get('host')}`
  const invite_link = `${appUrl}/invite/${token}`

  return NextResponse.json({ collaborator: inserted, invite_link }, { status: 201 })
}
